// operator:inventory — give every subagent a standard workspace (scripts/skills/
// schemas/subagents, alongside the eve-native tools/connections) and generate
// the agent + workflow inventory as inline markdown tables (docs/AGENT_INVENTORY.md).
//
//   npm run operator:inventory            # scaffold + regenerate the inventory doc
//   npm run operator:inventory -- --print # also print the tables to stdout
import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { hasFlag, glyph } from "./lib/operator.mjs";
import { fill } from "../../agent/lib/agent-vocabulary.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const subagentsDir = join(root, "agent", "subagents");
const workflowsDir = join(root, "scripts", "operator", "workflows");

// The workspace slots every subagent gets (tools/ + connections/ are eve-native
// and already present; these four standardize the rest).
const SLOTS = {
  scripts: "Helper scripts this subagent's skills/workflows call (organizational; not auto-loaded by eve).",
  skills: "Guided, step-at-a-time procedures for this subagent (SKILL.md files).",
  schemas: "JSON schemas for this subagent's inputs/outputs and the artifacts it writes.",
  subagents: "Nested subagents this one may delegate to — each a dir with its own agent.ts (eve discovers them here).",
};

function ensureWorkspace(dir) {
  for (const [slot, purpose] of Object.entries(SLOTS)) {
    const d = join(dir, slot);
    if (!existsSync(d)) mkdirSync(d, { recursive: true });
    const readme = join(d, "README.md");
    if (!existsSync(readme)) writeFileSync(readme, `# ${slot}/\n\n${purpose}\n`);
  }
}

function listDir(dir) {
  return existsSync(dir) ? readdirSync(dir) : [];
}
/** Real content = files other than README.md / .gitkeep. */
function hasContent(dir) {
  return listDir(dir).some((f) => f !== "README.md" && f !== ".gitkeep");
}
function toolNames(dir) {
  return listDir(dir).filter((f) => f.endsWith(".ts")).map((f) => f.replace(/\.ts$/, ""));
}
function first(re, s) {
  const m = re.exec(s);
  return m ? m[1] : null;
}
function trunc(s, n) {
  s = (s ?? "").replace(/\s+/g, " ").trim();
  return s.length > n ? s.slice(0, n - 1) + "…" : s;
}

// ---- Agent inventory ------------------------------------------------------
const agents = [];
for (const id of readdirSync(subagentsDir).filter((f) => statSync(join(subagentsDir, f)).isDirectory()).sort()) {
  const dir = join(subagentsDir, id);
  ensureWorkspace(dir);
  const agentTs = existsSync(join(dir, "agent.ts")) ? readFileSync(join(dir, "agent.ts"), "utf8") : "";
  const description = first(/description:\s*\n?\s*"([^"]+)"/, agentTs) ?? first(/description:\s*"([^"]+)"/, agentTs);
  const role = /agentModel\("orchestrator"\)/.test(agentTs) ? "orchestrator" : /agentModel\("specialist"\)/.test(agentTs) ? "specialist" : "—";
  const tools = toolNames(join(dir, "tools"));
  const connections = toolNames(join(dir, "connections"));
  const slots = Object.keys(SLOTS).filter((s) => hasContent(join(dir, s)));
  agents.push({ id, role, description, tools, connections, slots });
}

// ---- Workflow inventory ---------------------------------------------------
const workflows = [];
for (const f of listDir(workflowsDir).filter((f) => f.endsWith(".workflow.js")).sort()) {
  const src = readFileSync(join(workflowsDir, f), "utf8");
  const name = first(/name:\s*"([^"]+)"/, src);
  // In this deployment's words: the library writes role placeholders ({owner}, {member}) the profile fills.
  const raw = first(/description:\s*"([^"]+)"/, src);
  const description = raw === null ? null : fill(raw);
  const phases = [...src.matchAll(/phase\("([^"]+)"\)/g)].map((m) => m[1]);
  const subs = [...new Set([...src.matchAll(/subagent:\s*"([^"]+)"/g)].map((m) => m[1]))];
  workflows.push({ name, description, phases, subs });
}

// ---- Render markdown ------------------------------------------------------
const agentRows = agents.map(
  (a) =>
    `| \`${a.id}\` | ${a.role} | ${trunc(a.description, 90)} | ${a.tools.length} | ${a.connections.join(", ") || "—"} | ${["tools", "connections", ...a.slots].join(" · ")} |`,
);
const wfRows = workflows.map(
  (w) => `| \`${w.name}\` | ${trunc(w.description, 80)} | ${w.phases.join(" → ") || "—"} | ${w.subs.join(", ") || "—"} |`,
);

const md = `# Agent & workflow inventory

_Generated by \`npm run operator:inventory\` — do not edit by hand._

Every subagent has a standard workspace: \`tools/\` + \`connections/\` (eve-native) plus \`scripts/\`, \`skills/\`, \`schemas/\`, \`subagents/\`.

## Agent inventory (${agents.length} subagents)

| Subagent | Role | Purpose | Tools | Connections | Workspace |
| --- | --- | --- | --: | --- | --- |
${agentRows.join("\n")}

## Workflow inventory (${workflows.length} workflows)

| Workflow | Purpose | Phases | Subagents used |
| --- | --- | --- | --- |
${wfRows.join("\n")}
`;

const outPath = join(root, "docs", "AGENT_INVENTORY.md");
writeFileSync(outPath, md);
console.log(`${glyph.ok} scaffolded ${agents.length} subagent workspaces; wrote docs/AGENT_INVENTORY.md (${workflows.length} workflows).`);
if (hasFlag("print")) console.log("\n" + md);
