// operator:library-apply — give a workspace that ALREADY EXISTS the starter apps of this build's library.
//
//   npm run operator:library-apply                        # DRY RUN, every workspace: what would be added, what would not and why
//   npm run operator:library-apply -- --org <id>          # one workspace
//   npm run operator:library-apply -- --org <id> --apply  # create the apps listed as "would add"; nothing else
//   npm run operator:library-apply -- --json              # the same plan as JSON on stdout
//
// A NEW workspace is created with its library's starter apps (agent/lib/provision-workspace.ts). A workspace that
// existed before the library shipped them, or before the profile named the library, is never changed by a deploy:
// this command is the only way it gets them, and it shows what it would do first. Nothing is written without --apply.
//
// It uses the same function provisioning does (provisionStarterApps), so the same rules hold:
//   - an app the workspace already has (by its starter key) is left exactly as it is;
//   - a starter app a person deleted is NOT created again;
//   - an app is not created when the workspace already has one of that name, or does not hold the row that generates
//     it (operator:seed-workflows / operator:seed-subagent-rows add those);
//   - nothing is generated: each app's first document is written when a person first opens it, or on its schedule.
//     (`first_content: "on_create"` applies to a workspace being created, where there is a person to run it as.)
// Running it twice adds nothing the second time.
import { getDb, closeDb, withOrgDb } from "../../agent/lib/db/index.ts";
import * as schema from "../../agent/lib/db/schema.ts";
import { provisionStarterApps } from "../../agent/lib/provision-workspace.ts";
import { deploymentStarterApps } from "../../agent/lib/workflow-library-view.ts";
import { LIBRARY_SOURCES, STARTER_APP_LIBRARY } from "../../agent/lib/workflow-library.generated.ts";
import { flag, glyph, hasFlag } from "./lib/operator.mjs";
import { eq } from "drizzle-orm";

async function main() {
  const apply = hasFlag("apply");
  const json = hasFlag("json");
  const only = flag("org").trim();
  const starterApps = deploymentStarterApps();
  const say = (line = "") => { if (!json) console.log(line); };
  if (!starterApps.length) {
    const why = !LIBRARY_SOURCES.length
      ? `The profile of this build names no library source (library.sources is empty), so there are no starter apps to add. See docs/DEPLOYMENT_PROFILE.md, "library".`
      : !STARTER_APP_LIBRARY.length
        ? `The library of this build (${LIBRARY_SOURCES.join(", ")}) ships no starter apps (no apps.json), so there is nothing to add.`
        : `None of the ${STARTER_APP_LIBRARY.length} starter app(s) of ${LIBRARY_SOURCES.join(", ")} can be generated in this build, so there is nothing to add.`;
    if (json) console.log(JSON.stringify({ applied: false, library: LIBRARY_SOURCES, starterApps: [], workspaces: [] }, null, 2));
    else say(`${glyph.info} ${why}`);
    return;
  }
  const db = getDb();
  if (!db) {
    console.error(`${glyph.bad} No DATABASE_URL — run with --env-file=.env.local.`);
    process.exit(1);
  }
  const all = only
    ? await db.select({ orgId: schema.orgs.orgId, name: schema.orgs.name }).from(schema.orgs).where(eq(schema.orgs.orgId, only))
    : await db.select({ orgId: schema.orgs.orgId, name: schema.orgs.name }).from(schema.orgs);
  if (only && !all.length) {
    console.error(`${glyph.bad} No such workspace: ${only}`);
    await closeDb();
    process.exit(1);
  }
  say(apply ? "ADDING" : "DRY RUN (nothing is changed; add --apply to create what is listed as \"would add\")");
  say(`The library of this build: ${LIBRARY_SOURCES.join(", ")}. Its starter apps (${starterApps.length}):`);
  for (const a of starterApps) say(`  ${glyph.info} ${a.name}  — generated by ${a.sourceKind === "specialist" ? "the specialist" : "the workflow"} ${a.source}; ${a.refreshCron ? `refreshed on ${a.refreshCron} (UTC)` : "refreshed on request"}`);
  const report = [];
  for (const org of all.sort((a, b) => a.orgId.localeCompare(b.orgId))) {
    const result = await withOrgDb(org.orgId, (tx) => provisionStarterApps(tx, org.orgId, starterApps, { dryRun: !apply }));
    report.push({ workspace: org.orgId, ...result });
    say(`\n${org.orgId}  (${org.name})`);
    say(`  ${apply ? "added" : "would add"} (${result.created.length}):`);
    for (const a of result.created) say(`    ${glyph.ok} ${a.name}`);
    if (result.skipped.length) {
      say(`  left alone (${result.skipped.length}):`);
      for (const a of result.skipped) say(`    ${a.why === "present" ? glyph.info : glyph.warn} ${a.name}  — ${a.detail}`);
    }
  }
  if (json) console.log(JSON.stringify({ applied: apply, library: LIBRARY_SOURCES, starterApps: starterApps.map((a) => a.key), workspaces: report }, null, 2));
  else if (!apply && report.some((r) => r.created.length)) say(`\nNothing was changed. To add the apps listed: npm run operator:library-apply -- ${only ? `--org ${only} ` : ""}--apply`);
  else if (apply) say(`\nNo document was generated: each app's first one is written when a person first opens it, or on its schedule.`);
  await closeDb();
}

main().catch(async (e) => {
  console.error(`${glyph.bad} library-apply failed: ${e instanceof Error ? e.message : String(e)}`);
  await closeDb().catch(() => {});
  process.exit(1);
});
