CREATE TYPE "public"."memory_scope" AS ENUM('team', 'customer', 'person');--> statement-breakpoint
CREATE TYPE "public"."memory_sensitivity" AS ENUM('internal', 'customer_shareable', 'restricted');--> statement-breakpoint
CREATE TABLE "customer_stakeholders" (
	"customer_id" text NOT NULL,
	"stakeholder_role" text NOT NULL,
	"name" text NOT NULL,
	"title" text,
	"employer_org" text NOT NULL,
	"email" text NOT NULL,
	"last_contact" text,
	CONSTRAINT "customer_stakeholders_customer_id_stakeholder_role_email_pk" PRIMARY KEY("customer_id","stakeholder_role","email")
);
--> statement-breakpoint
CREATE TABLE "customers" (
	"customer_id" text PRIMARY KEY NOT NULL,
	"customer_name" text NOT NULL,
	"tier" text,
	"lifecycle_stage" text,
	"status" text,
	"health_score" double precision,
	"fde_owner" text,
	"ae_owner" text,
	"arr" double precision,
	"arr_currency" text,
	"seats" integer,
	"external_account_id" text,
	"legal_entity_name" text,
	"account_region" text,
	"contract_status" text,
	"renewal_forecast" text,
	"renewal_risk_reason" text,
	"expansion_potential_arr" double precision,
	"health_reason" text,
	"company_domain" text,
	"vertical" text,
	"regulatory_profile" text,
	"business_owner_email" text,
	"technical_owner_email" text,
	"executive_sponsor_email" text,
	"value_realization_stage" text,
	"target_annual_value" double precision,
	"realized_annual_value" double precision,
	"success_criteria" text,
	"value_period_start" text,
	"value_period_end" text,
	"value_evidence_status" text,
	"value_evidence_url" text,
	"last_business_review_date" text,
	"next_business_review_date" text,
	"contract_start" text,
	"renewal_date" text,
	"industry_segment" text
);
--> statement-breakpoint
CREATE TABLE "deployments" (
	"customer_id" text NOT NULL,
	"deployment_id" text NOT NULL,
	"environment" text NOT NULL,
	"region" text NOT NULL,
	"cloud_provider" text,
	"runtime" text,
	"deployment_strategy" text,
	"deployed_version" text NOT NULL,
	"release_id" text,
	"release_channel" text,
	"build_sha" text,
	"runtime_version" text,
	"config_version" text,
	"approved_by_email" text,
	"approved_at" text,
	"model_route_id" text,
	"model_routing_mode" text,
	"primary_model_ref" text,
	"primary_model_version" text,
	"fallback_model_ref" text,
	"fallback_model_version" text,
	"model_traffic_primary_pct" double precision,
	"last_deploy_at" text,
	"release_status" text NOT NULL,
	"rollback_version" text,
	"rollback_status" text,
	"rollback_tested_at" text,
	"health_status" text NOT NULL,
	"uptime_30d_pct" double precision,
	"error_rate_30d_pct" double precision,
	"latency_p95_ms" double precision,
	"latency_slo_ms" double precision,
	"request_count_30d" bigint,
	"llm_request_count_30d" bigint,
	"input_tokens_30d" bigint,
	"output_tokens_30d" bigint,
	"cache_hit_rate_30d_pct" double precision,
	"guardrail_block_rate_30d_pct" double precision,
	"cost_30d_usd" double precision,
	"cost_budget_30d_usd" double precision,
	"projected_cost_30d_usd" double precision,
	"capacity_limit_rpm" integer,
	"peak_rpm_30d" integer,
	"utilization_30d_pct" double precision,
	"live_url" text,
	"deploy_owner_email" text,
	"last_incident_ref" text,
	"active_incident_refs" jsonb,
	"incident_count_30d" integer,
	"dashboard_url" text,
	"runbook_url" text,
	"last_telemetry_at" text,
	"notes" text,
	CONSTRAINT "deployments_customer_id_deployment_id_pk" PRIMARY KEY("customer_id","deployment_id")
);
--> statement-breakpoint
CREATE TABLE "implementation" (
	"customer_id" text PRIMARY KEY NOT NULL,
	"rollout_id" text,
	"launch_scope_solution_ids" jsonb,
	"implementation_stage" text NOT NULL,
	"implementation_owner_email" text,
	"rollout_governance_status" text,
	"customer_launch_approver_email" text,
	"onfinance_launch_approver_email" text,
	"launch_decision" text,
	"launch_decision_date" text,
	"implementation_progress_pct" double precision NOT NULL,
	"implementation_risk_level" text NOT NULL,
	"data_readiness_pct" double precision,
	"integration_readiness_pct" double precision,
	"data_source_inventory_status" text,
	"data_access_status" text,
	"data_quality_status" text,
	"connector_provisioning_status" text,
	"integration_test_status" text,
	"security_review_status" text,
	"privacy_review_status" text,
	"eval_acceptance_status" text,
	"acceptance_evidence_link" text,
	"uat_status" text,
	"training_status" text,
	"launch_criteria" text,
	"launch_criteria_status" text,
	"go_live_confidence_pct" double precision,
	"target_go_live_date" text,
	"actual_go_live_date" text,
	"launch_window_start_at" text,
	"launch_window_end_at" text,
	"runbook_status" text,
	"runbook_link" text,
	"support_handoff_status" text,
	"support_owner_email" text,
	"support_channel_ref" text,
	"billing_readiness_status" text,
	"entitlement_provisioning_status" text,
	"billing_start_date" text,
	"current_milestone" text,
	"current_milestone_due_date" text,
	"blocker" text,
	"blocker_owner" text NOT NULL,
	"blocker_severity" text,
	"blocked_since_date" text,
	"risk_mitigation_plan" text,
	"critical_blocker_ticket_ids" jsonb,
	"open_blocker_count" integer,
	"implementation_next_step" text,
	"implementation_last_updated_at" text
);
--> statement-breakpoint
CREATE TABLE "interactions" (
	"customer_id" text NOT NULL,
	"interaction_id" text NOT NULL,
	"interaction_at" text NOT NULL,
	"interaction_type" text NOT NULL,
	"source_system" text NOT NULL,
	"source_id" text,
	"source_link" text,
	"summary" text,
	"note" text NOT NULL,
	"outcome" text,
	"participant_emails" jsonb,
	"related_ticket_ids" jsonb,
	"related_solution_ids" jsonb,
	"related_deployment_ids" jsonb,
	"next_action" text,
	"next_action_owner_email" text,
	"next_action_due_date" text,
	"sentiment" text,
	"sensitivity" text,
	"recorded_by_email" text,
	"recorded_at" text,
	CONSTRAINT "interactions_customer_id_interaction_id_pk" PRIMARY KEY("customer_id","interaction_id")
);
--> statement-breakpoint
CREATE TABLE "internal_staff" (
	"customer_id" text NOT NULL,
	"staff_role" text NOT NULL,
	"name" text NOT NULL,
	"title" text,
	"employer_org" text NOT NULL,
	"email" text NOT NULL,
	"last_contact" text,
	CONSTRAINT "internal_staff_customer_id_staff_role_email_pk" PRIMARY KEY("customer_id","staff_role","email")
);
--> statement-breakpoint
CREATE TABLE "memories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"scope" "memory_scope" NOT NULL,
	"entity_id" text,
	"key" text NOT NULL,
	"value" text NOT NULL,
	"author_email" text NOT NULL,
	"sensitivity" "memory_sensitivity" DEFAULT 'internal' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform" (
	"customer_id" text PRIMARY KEY NOT NULL,
	"tenant_id" text,
	"platform_config_status" text,
	"deployment_model" text NOT NULL,
	"data_residency_constraint" text NOT NULL,
	"auth_mode" text,
	"data_classification" text,
	"pii_handling" text,
	"audit_logging_enabled" boolean,
	"retention_days" integer,
	"ai_governance_status" text,
	"model_policy_id" text,
	"allowed_model_providers" jsonb,
	"model_data_use_policy" text,
	"inference_region" text,
	"cross_border_processing_allowed" boolean,
	"guardrail_policy" text,
	"guardrail_policy_version" text,
	"guardrail_enforcement_mode" text,
	"prompt_logging_mode" text,
	"customer_managed_key_enabled" boolean,
	"kms_key_ref" text,
	"scim_provisioning_enabled" boolean,
	"rbac_policy" text,
	"audit_log_sink" text,
	"observability_enabled" boolean,
	"primary_model" text NOT NULL,
	"fallback_model" text,
	"minimum_eval_score_pct" double precision,
	"last_governance_review_at" text,
	"monthly_spend_limit_usd" double precision,
	"enabled_connectors" jsonb NOT NULL,
	"feature_flags" jsonb NOT NULL,
	"primary_use_case" text NOT NULL,
	"last_health_check_at" text
);
--> statement-breakpoint
CREATE TABLE "solutions" (
	"customer_id" text NOT NULL,
	"solution_id" text NOT NULL,
	"use_case" text NOT NULL,
	"workflow_id" text,
	"workflow_name" text,
	"business_process" text,
	"business_unit" text,
	"primary_user_role" text,
	"workflow_owner_email" text,
	"risk_owner_email" text,
	"workflow_frequency" text,
	"decision_impact" text,
	"upstream_systems" jsonb,
	"downstream_systems" jsonb,
	"output_artifacts" jsonb,
	"sensitive_data_types" jsonb,
	"value_metric" text,
	"value_metric_unit" text,
	"value_metric_direction" text,
	"measurement_source" text,
	"measurement_window_days" integer,
	"baseline_metric_value" double precision,
	"current_metric_value" double precision,
	"target_metric_value" double precision,
	"baseline_period_start" text,
	"baseline_period_end" text,
	"current_period_start" text,
	"current_period_end" text,
	"target_date" text,
	"value_evidence_url" text,
	"annualized_value_realized_usd" double precision,
	"value_realization_confidence_pct" double precision,
	"solution_value_realization_stage" text,
	"modules_enabled" jsonb NOT NULL,
	"solution_status" text NOT NULL,
	"solution_go_live_date" text,
	"weekly_active_users" integer,
	"weekly_query_volume" integer,
	"automation_rate_pct" double precision,
	"human_review_rate_pct" double precision,
	"production_readiness_score" double precision,
	"solution_eval_score_pct" double precision,
	"eval_status" text,
	"eval_suite_id" text,
	"eval_dataset_version" text,
	"last_eval_run_id" text,
	"last_eval_run_at" text,
	"eval_pass_rate_pct" double precision,
	"eval_coverage_pct" double precision,
	"task_success_rate_pct" double precision,
	"answer_acceptance_rate_pct" double precision,
	"groundedness_score_pct" double precision,
	"citation_coverage_pct" double precision,
	"hallucination_rate_pct" double precision,
	"policy_violation_rate_pct" double precision,
	"guardrail_intervention_rate_pct" double precision,
	"customer_reported_defects_30d" integer,
	"safety_incident_count_30d" integer,
	"human_review_policy" text,
	"review_sla_hours" double precision,
	"review_sla_attainment_pct" double precision,
	"review_backlog_count" integer,
	"readiness_status" text,
	"readiness_gate_failures" jsonb,
	"model_risk_approval_status" text,
	"runbook_url" text,
	"solution_next_step" text,
	"last_eval_run" text,
	"value_delivered" text,
	"expansion_opportunity" text,
	"expansion_stage" text,
	"expansion_potential_annual_value_usd" double precision,
	"expansion_confidence_pct" double precision,
	"solution_fde_owner" text NOT NULL,
	"last_reviewed_date" text,
	CONSTRAINT "solutions_customer_id_solution_id_pk" PRIMARY KEY("customer_id","solution_id")
);
--> statement-breakpoint
CREATE TABLE "tickets" (
	"customer_id" text NOT NULL,
	"ticket_id" text NOT NULL,
	"summary" text NOT NULL,
	"description" text,
	"affected_schema" text,
	"affected_solution_id" text,
	"affected_deployment_id" text,
	"affected_environment" text,
	"affected_workflow_id" text,
	"affected_connector" text,
	"affected_model" text,
	"affected_data_source" text,
	"related_ticket_ids" jsonb,
	"external_system" text,
	"external_id" text,
	"ticket_type" text NOT NULL,
	"ticket_category" text NOT NULL,
	"ticket_status" text NOT NULL,
	"ticket_priority" text NOT NULL,
	"severity" text,
	"support_queue" text,
	"owner_team" text,
	"reported_by_email" text,
	"customer_contact_email" text,
	"ticket_opened_date" text NOT NULL,
	"triaged_at" text,
	"ticket_due_date" text,
	"sla_due_at" text,
	"first_response_due_at" text,
	"first_responded_at" text,
	"resolution_due_at" text,
	"sla_status" text,
	"escalated" boolean,
	"escalated_at" text,
	"escalation_level" text,
	"escalation_reason" text,
	"ticket_owner_email" text NOT NULL,
	"source_channel" text NOT NULL,
	"last_activity_date" text NOT NULL,
	"source_link" text,
	"escalation_owner_email" text,
	"production_impact" boolean,
	"customer_impact_level" text,
	"customer_impact_summary" text,
	"affected_user_count" integer,
	"issue_domain" text,
	"model_issue_type" text,
	"data_issue_type" text,
	"integration_issue_type" text,
	"root_cause_status" text,
	"root_cause_category" text,
	"root_cause_summary" text,
	"detected_at" text,
	"mitigated_at" text,
	"remediation_summary" text,
	"preventive_actions" text,
	"postmortem_required" boolean,
	"postmortem_status" text,
	"postmortem_owner_email" text,
	"postmortem_due_date" text,
	"postmortem_url" text,
	"tags" jsonb,
	"resolution_summary" text,
	"resolved_at" text,
	"ticket_next_step" text NOT NULL,
	CONSTRAINT "tickets_customer_id_ticket_id_pk" PRIMARY KEY("customer_id","ticket_id")
);
--> statement-breakpoint
ALTER TABLE "customer_stakeholders" ADD CONSTRAINT "customer_stakeholders_customer_id_customers_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("customer_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deployments" ADD CONSTRAINT "deployments_customer_id_customers_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("customer_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "implementation" ADD CONSTRAINT "implementation_customer_id_customers_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("customer_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interactions" ADD CONSTRAINT "interactions_customer_id_customers_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("customer_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "internal_staff" ADD CONSTRAINT "internal_staff_customer_id_customers_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("customer_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "platform" ADD CONSTRAINT "platform_customer_id_customers_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("customer_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solutions" ADD CONSTRAINT "solutions_customer_id_customers_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("customer_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_customer_id_customers_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("customer_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "customer_stakeholders_email_idx" ON "customer_stakeholders" USING btree ("email");--> statement-breakpoint
CREATE INDEX "customers_fde_owner_idx" ON "customers" USING btree ("fde_owner");--> statement-breakpoint
CREATE INDEX "customers_lifecycle_stage_idx" ON "customers" USING btree ("lifecycle_stage");--> statement-breakpoint
CREATE INDEX "deployments_customer_id_idx" ON "deployments" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "deployments_health_status_idx" ON "deployments" USING btree ("health_status");--> statement-breakpoint
CREATE INDEX "interactions_customer_id_idx" ON "interactions" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "interactions_interaction_at_idx" ON "interactions" USING btree ("interaction_at");--> statement-breakpoint
CREATE INDEX "internal_staff_email_idx" ON "internal_staff" USING btree ("email");--> statement-breakpoint
CREATE INDEX "memories_scope_entity_id_idx" ON "memories" USING btree ("scope","entity_id");--> statement-breakpoint
CREATE INDEX "memories_key_idx" ON "memories" USING btree ("key");--> statement-breakpoint
CREATE INDEX "solutions_customer_id_idx" ON "solutions" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "solutions_solution_status_idx" ON "solutions" USING btree ("solution_status");--> statement-breakpoint
CREATE INDEX "tickets_customer_id_idx" ON "tickets" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "tickets_ticket_status_idx" ON "tickets" USING btree ("ticket_status");--> statement-breakpoint
CREATE INDEX "tickets_ticket_category_idx" ON "tickets" USING btree ("ticket_category");