// AUTO-GENERATED by scripts/gen-deployment-profile.mjs from scripts/lib/legacy-dataroom-folders.json — do not edit by hand.
import type { DataroomDomainId } from "./deployment-profile.generated.ts";

/**
 * The names the data-room folders had while they were written into the code, by domain id. A data room that holds
 * one of these while the profile stores that domain under another name was filled before the profile said where:
 * it is refused (agent/lib/dataroom-folders.ts), never silently forked.
 */
export const LEGACY_DATAROOM_FOLDERS: Record<DataroomDomainId | "uploads", string> = {"accounts":"Customers","platform":"Platform","deliveries":"Deployments","solutions":"Solutions","projects":"Implementation","tickets":"Tickets","people":"People","uploads":"Uploads"};
