// GENERATED by scripts/build-workflow-library.mjs — do not edit by hand.
// Source: the deployment profile's library.sources (none): 0 workflows, 0 recipes
//
// Regenerate with: npm run build:workflow-library

export interface LibraryWorkflow {
  readonly name: string;
  readonly description: string;
  readonly steps: readonly string[];
  readonly script: string;
}

export interface LibraryRecipe {
  readonly slug: string;
  readonly title: string;
  readonly summary: string | null;
  /** The workspace health check this recipe turns green, when it has one. */
  readonly satisfiesCheck: string | null;
}

/** The ids under the profile's library.sources this file was built from. Empty: this deployment provisions no library. */
export const LIBRARY_SOURCES: readonly string[] = [];

export const WORKFLOW_LIBRARY: readonly LibraryWorkflow[] = [] as const;

export const RECIPE_LIBRARY: readonly LibraryRecipe[] = [] as const;
