// GENERATED by scripts/build-workflow-library.mjs — do not edit by hand.
// Source: scripts/operator/workflows/*.workflow.js  (13 workflows)
//
// Regenerate with: npm run build:workflow-library

export interface LibraryWorkflow {
  readonly name: string;
  readonly description: string;
  readonly steps: readonly string[];
  readonly script: string;
}

export const WORKFLOW_LIBRARY: readonly LibraryWorkflow[] = [
  {
    "name": "assign-account",
    "description": "Propose and (on confirmation) set the durable FDE owner for a new or unowned customer.",
    "steps": [
      "Propose"
    ],
    "script": "export const meta = {\n  name: \"assign-account\",\n  description: \"Propose and (on confirmation) set the durable FDE owner for a new or unowned customer.\",\n};\n\nconst c = (args && args.customerId) || \"\";\n\nphase(\"Propose\");\nconst proposal = await agent(\n  \"Choose the best FDE owner for customer \" + c + \". Call list_fdes for the roster with live load; pick the least-loaded FDE (accounts owned + open tickets vs their capacity target) whose skills match this account's product/regime. Present the recommendation with rationale and the runner-up. Do NOT reassign yet — this is a proposal for a human to confirm.\",\n  { subagent: \"customer-context\" },\n);\n\nlog(\"assign-account proposed an owner for \" + c);\nreturn { proposal };\n"
  },
  {
    "name": "data-migration-plan",
    "description": "Plan a customer data migration: source, mapping, volume, validation, rollback.",
    "steps": [
      "Plan"
    ],
    "script": "export const meta = {\n  name: \"data-migration-plan\",\n  description: \"Plan a customer data migration: source, mapping, volume, validation, rollback.\",\n};\n\nconst c = (args && args.customerId) || \"\";\nconst source = (args && args.source) || \"the legacy source described by the customer\";\n\nphase(\"Plan\");\nconst plan = await agent(\n  \"Plan a data migration for customer \" + c + \" from \" + source + \". Produce: source inventory, field mapping, volume estimate, a staging-first execution plan, validation (row counts + spot checks), and a rollback plan. Treat the data as sensitive and irreversible — require human approval before any execution. Write the approach under Implementation/\" + c + \"/migrations/{id}/.\",\n  { subagent: \"data-migration\" },\n);\n\nlog(\"data-migration-plan complete for \" + c);\nreturn { plan };\n"
  },
  {
    "name": "eval-regression-triage",
    "description": "Run a customer's eval suite, interpret regressions, and file fix tickets.",
    "steps": [
      "Run + interpret",
      "Triage"
    ],
    "script": "export const meta = {\n  name: \"eval-regression-triage\",\n  description: \"Run a customer's eval suite, interpret regressions, and file fix tickets.\",\n};\n\nconst c = (args && args.customerId) || \"\";\n\nphase(\"Run + interpret\");\nconst findings = await agent(\n  \"Run the eval suite for customer \" + c + \" (or the latest run's outputs), compare against the benchmark, and identify regressions: which cases got worse, by how much, and the likely cause. Return the regressions ranked by severity.\",\n  { subagent: \"evals\" },\n);\n\nphase(\"Triage\");\nconst triage = await agent(\n  \"From these eval regressions for \" + c + \", file a fix ticket per real regression (owned by the customer's fde_owner, priority by severity) and post a short triage summary. Regressions follow.\\n\\n\" + findings,\n  { subagent: \"follow-ups\" },\n);\n\nlog(\"eval-regression-triage complete for \" + c);\nreturn { findings, triage };\n"
  },
  {
    "name": "go-live-sprint",
    "description": "Assess a deployment's readiness, build the go-live runbook, and file blocker tickets with owners.",
    "steps": [
      "Assess",
      "Runbook",
      "Blockers"
    ],
    "script": "export const meta = {\n  name: \"go-live-sprint\",\n  description: \"Assess a deployment's readiness, build the go-live runbook, and file blocker tickets with owners.\",\n};\n\nconst c = (args && args.customerId) || \"\";\nconst ver = (args && args.platformVersionId) || \"v2.0\";\n\nphase(\"Assess\");\nconst readiness = await parallel([\n  () => agent(\"Report the deployment-tracker phase status and the 4-party signoff chain (internal, customer.infra, customer.infosec, customer.cloudvendor) for customer \" + c + \" platform \" + ver + \". Name what's incomplete.\", { subagent: \"deployment\" }),\n  () => agent(\"Report the data-migration state for customer \" + c + \": what's migrated, validated, and pending.\", { subagent: \"data-migration\" }),\n  () => agent(\"Report the latest eval/acceptance results for customer \" + c + \" and whether they pass the go-live bar.\", { subagent: \"evals\" }),\n]);\n\nphase(\"Runbook\");\nconst runbook = await agent(\n  \"Build the go-live runbook for customer \" + c + \" platform \" + ver + \" from this readiness assessment. Cover: 4-party signoff complete, data migration validated, evals passed, UAT signoff, DNS/SSO/SMTP/email integration, RBI/SEBI scraper configured, circulars processed, and rollback plan. Mark each item Ready/At-Risk/Blocked with the owner. Publish the runbook artifact. Readiness follows.\\n\\n\" + JSON.stringify(readiness),\n  { subagent: \"deployment\" },\n);\n\nphase(\"Blockers\");\nconst blockers = await agent(\n  \"From the go-live runbook for \" + c + \", file a ticket for each Blocked/At-Risk item (owned by the customer's fde_owner, priority by go-live impact) and post a ranked blocker list. Runbook follows.\\n\\n\" + runbook,\n  { subagent: \"follow-ups\" },\n);\n\nlog(\"go-live-sprint complete for \" + c);\nreturn { readiness, runbook, blockers };\n"
  },
  {
    "name": "incident-postmortem",
    "description": "Build a postmortem from an incident ticket and timeline.",
    "steps": [
      "Reconstruct",
      "Postmortem"
    ],
    "script": "export const meta = {\n  name: \"incident-postmortem\",\n  description: \"Build a postmortem from an incident ticket and timeline.\",\n};\n\nconst c = (args && args.customerId) || \"\";\nconst ticket = (args && args.ticketId) || \"the most recent P0/P1 incident\";\n\nphase(\"Reconstruct\");\nconst timeline = await agent(\n  \"Reconstruct the timeline for incident \" + ticket + \" (customer \" + c + \"): detection, mitigation, resolution, and the interactions/tickets along the way. Return the timeline and the customer impact.\",\n  { subagent: \"deployment\" },\n);\n\nphase(\"Postmortem\");\nconst postmortem = await agent(\n  \"Write a blameless postmortem for incident \" + ticket + \" (customer \" + c + \") from this timeline: root cause, contributing factors, remediation done, preventive actions with owners, and whether an SLA was breached. Record it into the ticket's postmortem fields and publish the doc. Timeline follows.\\n\\n\" + timeline,\n  { subagent: \"follow-ups\" },\n);\n\nlog(\"incident-postmortem complete for \" + ticket);\nreturn { timeline, postmortem };\n"
  },
  {
    "name": "infosec-checklist",
    "description": "Generate a customer's information-security checklist from their regulatory profile and map it to the infosec signoff.",
    "steps": [
      "Profile",
      "Generate",
      "Signoff"
    ],
    "script": "export const meta = {\n  name: \"infosec-checklist\",\n  description: \"Generate a customer's information-security checklist from their regulatory profile and map it to the infosec signoff.\",\n};\n\nconst c = (args && args.customerId) || \"\";\nconst ver = (args && args.platformVersionId) || \"v2.0\";\n\nphase(\"Profile\");\nconst profile = await agent(\n  \"Read customer \" + c + \" regulatory + security profile from context.md and the system of record: their regime (RBI/SEBI/IRDAI/other), data-residency requirements, deployment substrate, and any stated security asks. Return a concise profile.\",\n  { subagent: \"research\" },\n);\n\nphase(\"Generate\");\nconst checklist = await agent(\n  \"Generate the information-security checklist/questionnaire for customer \" + c + \" (platform \" + ver + \") from this profile and the platform security schemas. Cover: SBOM, RBAC/least-privilege, encryption at rest + in transit, key management, data residency, audit logging, vulnerability management + pen-test, access reviews, DR/BCP (RTO/RPO), and incident response. Mark each item required/optional for their regime, and write it to the deployment's security/ folder. Profile follows.\\n\\n\" + profile,\n  { subagent: \"configuration\" },\n);\n\nphase(\"Signoff\");\nconst signoff = await agent(\n  \"Record the customer.infosec signoff item for customer \" + c + \" platform \" + ver + \" referencing the infosec checklist just generated, set to PENDING, and publish the checklist as a shareable artifact. Return the artifact link and signoff status.\",\n  { subagent: \"deployment\" },\n);\n\nlog(\"infosec-checklist complete for \" + c);\nreturn { profile, checklist, signoff };\n"
  },
  {
    "name": "infra-sizing",
    "description": "Size a customer deployment's infrastructure across the 8 components and emit customizations.tf + rationale.",
    "steps": [
      "Gather",
      "Size",
      "Emit"
    ],
    "script": "export const meta = {\n  name: \"infra-sizing\",\n  description: \"Size a customer deployment's infrastructure across the 8 components and emit customizations.tf + rationale.\",\n};\n\nconst c = (args && args.customerId) || \"\";\nconst ver = (args && args.platformVersionId) || \"v2.0\";\n\nphase(\"Gather\");\nconst scale = await agent(\n  \"Read the scale signals for customer \" + c + \" from their context.md and the system of record: expected users, request volume/throughput, data size, availability target, regulatory/data-residency constraints, and deployment substrate (AWS/Azure/GCP/on-prem/bare-metal). Return a concise scale profile.\",\n  { subagent: \"research\" },\n);\n\nphase(\"Size\");\nconst sizing = await agent(\n  \"Size the deployment infrastructure for customer \" + c + \" platform \" + ver + \" from this scale profile. For EACH of the 8 components — network, compute, storage, inference, agents, database, observability, autoscale — specify the sizing (instance classes, counts, storage, autoscale bounds) and write customizations.tf + rationale.md under Deployments/\" + c + \"/\" + ver + \"/infrastructure/{component}/. Keep infra-tier SLA targets (uptime/RTO/RPO) in mind. Scale profile follows.\\n\\n\" + scale,\n  { subagent: \"deployment\" },\n);\n\nphase(\"Emit\");\nconst report = await agent(\n  \"Publish a one-page infra sizing report for customer \" + c + \" platform \" + ver + \": the per-component sizing, the rationale, and any cost/scale risks. Return the artifact link.\",\n  { subagent: \"deployment\" },\n);\n\nlog(\"infra-sizing complete for \" + c);\nreturn { scale, sizing, report };\n"
  },
  {
    "name": "integration-wiring",
    "description": "Wire a customer's pipelines / Integromat integrations and land the config.",
    "steps": [
      "Wire"
    ],
    "script": "export const meta = {\n  name: \"integration-wiring\",\n  description: \"Wire a customer's pipelines / Integromat integrations and land the config.\",\n};\n\nconst c = (args && args.customerId) || \"\";\n\nphase(\"Wire\");\nconst wiring = await agent(\n  \"Wire the pipeline / Integromat integrations for customer \" + c + \". Define the pipeline_config and integromat scenario, land them under Implementation/\" + c + \"/pipelines/ and Implementation/\" + c + \"/integromat.json. Put any credentials in private.integromat.json (never publish those). Flag risky changes for approval. Summarize what was wired.\",\n  { subagent: \"configuration\" },\n);\n\nlog(\"integration-wiring complete for \" + c);\nreturn { wiring };\n"
  },
  {
    "name": "onboard-account",
    "description": "End-to-end onboard a new customer: seed context, research, and assign an owner.",
    "steps": [
      "Seed",
      "Research",
      "Assign owner"
    ],
    "script": "export const meta = {\n  name: \"onboard-account\",\n  description: \"End-to-end onboard a new customer: seed context, research, and assign an owner.\",\n};\n\nconst c = (args && args.customerId) || \"\";\nconst name = (args && args.customerName) || c;\n\nphase(\"Seed\");\nconst seeded = await agent(\n  \"Onboard new customer \" + c + \" (\" + name + \"): confirm/create the customer record at lifecycle Onboarding, seed Customers/\" + c + \"/context.md from what's known, and log an account-created interaction. Return what was seeded.\",\n  { subagent: \"customer-context\" },\n);\n\nphase(\"Research\");\nconst research = await agent(\n  \"Research the newly onboarded account \" + c + \" to enrich its system of record and context: use case, org map, scale, regulatory profile. Return a concise account brief.\",\n  { subagent: \"research\" },\n);\n\nphase(\"Assign owner\");\nconst assignment = await agent(\n  \"Recommend the best FDE owner for customer \" + c + \": call list_fdes, pick the least-loaded FDE whose skills match this account's product/regime, and propose the assignment with rationale for a human to confirm (do not force it). Return the recommendation.\",\n  { subagent: \"customer-context\" },\n);\n\nlog(\"onboard-account complete for \" + c);\nreturn { seeded, research, assignment };\n"
  },
  {
    "name": "qbr-prep",
    "description": "Prepare a customer QBR: interactions, tickets, health, value realization into a report.",
    "steps": [
      "Gather",
      "Compose"
    ],
    "script": "export const meta = {\n  name: \"qbr-prep\",\n  description: \"Prepare a customer QBR: interactions, tickets, health, value realization into a report.\",\n};\n\nconst c = (args && args.customerId) || \"\";\n\nphase(\"Gather\");\nconst gathered = await agent(\n  \"Gather the QBR inputs for customer \" + c + \": recent interactions, open + resolved tickets, health/status, SLA posture, and value-realization (target vs realized annual value, success criteria). Return a structured summary.\",\n  { subagent: \"customer-context\" },\n);\n\nphase(\"Compose\");\nconst deck = await agent(\n  \"Compose a QBR report for customer \" + c + \" from these inputs: where they are, wins, open risks, SLA/health, value delivered vs target, and the next-quarter plan. Publish it as an artifact. Inputs follow.\\n\\n\" + gathered,\n  { subagent: \"follow-ups\" },\n);\n\nlog(\"qbr-prep complete for \" + c);\nreturn { gathered, deck };\n"
  },
  {
    "name": "renewal-risk",
    "description": "Assess a customer's renewal risk and produce a save plan with owner actions.",
    "steps": [
      "Assess",
      "Save plan"
    ],
    "script": "export const meta = {\n  name: \"renewal-risk\",\n  description: \"Assess a customer's renewal risk and produce a save plan with owner actions.\",\n};\n\nconst c = (args && args.customerId) || \"\";\n\nphase(\"Assess\");\nconst assessment = await agent(\n  \"Assess renewal risk for customer \" + c + \": health trend, SLA breaches, ticket load, engagement/interaction recency, value realization vs target, and renewal date proximity. Return a risk level (low/medium/high) with the evidence.\",\n  { subagent: \"customer-context\" },\n);\n\nphase(\"Save plan\");\nconst plan = await agent(\n  \"From this renewal-risk assessment for \" + c + \", produce a save plan: the top risks, the specific actions to de-risk (with owners and due dates), and file follow-up tickets for the owner. Publish the plan. Assessment follows.\\n\\n\" + assessment,\n  { subagent: \"follow-ups\" },\n);\n\nlog(\"renewal-risk complete for \" + c);\nreturn { assessment, plan };\n"
  },
  {
    "name": "route-incident",
    "description": "Route a genuine incident (SLA breach / P0 / P1) to the on-call via PagerDuty.",
    "steps": [
      "Route"
    ],
    "script": "export const meta = {\n  name: \"route-incident\",\n  description: \"Route a genuine incident (SLA breach / P0 / P1) to the on-call via PagerDuty.\",\n};\n\nconst c = (args && args.customerId) || \"\";\nconst ticket = (args && args.ticketId) || \"\";\n\nphase(\"Route\");\nconst routed = await agent(\n  \"Route the incident for ticket \" + ticket + \" (customer \" + c + \") to on-call. Confirm it is a genuine P0/P1 or SLA breach; read get_oncall to name the responder; then page_oncall with dedupKey = the ticket id, severity by impact, and a one-line summary. Post a short note of who was paged. If it is not genuinely incident-grade, do not page — say so.\",\n  { subagent: \"follow-ups\" },\n);\n\nlog(\"route-incident complete for ticket \" + ticket);\nreturn { routed };\n"
  },
  {
    "name": "solution-engineering",
    "description": "Scope and design a reusable solution for a customer: research, design, seed evals, package.",
    "steps": [
      "Research",
      "Design",
      "Evals",
      "Package"
    ],
    "script": "export const meta = {\n  name: \"solution-engineering\",\n  description: \"Scope and design a reusable solution for a customer: research, design, seed evals, package.\",\n};\n\nconst c = (args && args.customerId) || \"\";\nconst ask = (args && args.request) || \"the customer's stated needs\";\n\nphase(\"Research\");\nconst research = await agent(\n  \"Research account \" + c + \" for a new solution. Ground on the system of record and recent interactions. Return: their use case, data sources, scale (users/volume/throughput), regulatory constraints, and the requirements for \" + ask + \". Keep it tight.\",\n  { subagent: \"research\" },\n);\n\nphase(\"Design\");\nconst design = await agent(\n  \"Design a solution for customer \" + c + \" from this research. Pick the platform version, define the schema contract and the agent/pipeline recipe, and write them under Solutions/{ver}/. Flag any risky/irreversible choices for human approval. Research follows.\\n\\n\" + research,\n  { subagent: \"configuration\" },\n);\n\nphase(\"Evals\");\nconst evals = await agent(\n  \"Seed acceptance evals (dataset + benchmark) for the solution just designed for \" + c + \". Place them under the solution's evals/ folder. Summarize what they check.\",\n  { subagent: \"evals\" },\n);\n\nphase(\"Package\");\nconst report = await agent(\n  \"Validate the \" + c + \" solution (schema parses, recipe filled, evals seeded) and publish a one-page solution design doc summarizing the design decisions, the recipe, and the eval coverage. Return the artifact link.\",\n  { subagent: \"configuration\" },\n);\n\nlog(\"solution-engineering complete for \" + c);\nreturn { research, design, evals, report };\n"
  }
] as const;
