// GENERATED by scripts/build-workflow-library.mjs — do not edit by hand.
// Source: the deployment profile's library.sources (none): 0 workflows, 0 recipes, 0 starter apps
//
// Regenerate with: npm run build:workflow-library

export interface LibraryWorkflow {
  readonly name: string;
  readonly description: string;
  readonly steps: readonly string[];
  readonly script: string;
}

export interface LibraryRecipe {
  readonly slug: string;
  readonly title: string;
  readonly summary: string | null;
  /** The workspace health check this recipe turns green, when it has one. */
  readonly satisfiesCheck: string | null;
}

/**
 * A STARTER APP: an app every NEW workspace of this deployment is created with (agent/lib/provision-workspace.ts).
 * The library's, never base code's: `<library>/apps.json` (scripts/lib/profile-library.mjs says how one is written
 * and what the build refuses).
 */
export interface LibraryStarterApp {
  /** `<library id>/<key>`: what a workspace's row carries (apps.starter_key), so it is created once and only once. */
  readonly key: string;
  readonly library: string;
  readonly name: string;
  readonly description: string;
  /** What the source is asked for at every refresh. */
  readonly brief: string;
  readonly sourceKind: "specialist" | "workflow";
  /** A specialist this build has, or a workflow of the same library. */
  readonly source: string;
  /** 5-field UTC cron, or null: refreshed on request only. */
  readonly refreshCron: string | null;
  /** When the first document is written: when a person first opens the app (or its schedule comes due), or when the workspace is created. */
  readonly firstContent: "on_open" | "on_create";
}

/** The ids under the profile's library.sources this file was built from. Empty: this deployment provisions no library. */
export const LIBRARY_SOURCES: readonly string[] = [];

export const WORKFLOW_LIBRARY: readonly LibraryWorkflow[] = [] as const;

export const RECIPE_LIBRARY: readonly LibraryRecipe[] = [] as const;

export const STARTER_APP_LIBRARY: readonly LibraryStarterApp[] = [] as const;
