#!/usr/bin/env node
// Compiles the agent's authored prompt Markdown into one TypeScript module every consumer can import:
//   agent/prompt-<name>.md          -> PROMPTS["<name>"]           (the root prompt's core, persona, neutral opening)
//   agent/subagents/<key>/prompt.md -> SUBAGENT_PROMPTS["<key>"]   (a base specialist's prompt)
// into agent/lib/prompts.generated.ts.
//
// Why generated, not read at run time: a prompt is rendered from the deployment profile at eve BUILD time
// (agent/instructions.ts, agent/subagents/<key>/instructions.ts, through agent/lib/agent-vocabulary.ts), eve
// evaluates those modules from a bundle with no Markdown loader, and the offline tests import the same renderer
// under plain Node. A module of string constants works in all three. Part of build:generated; check:generated
// fails when the committed file is stale.   npm run build:prompts
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
// At the agent root, not under agent/lib/: eve's discovery accepts only modules in lib/, and ignores a Markdown
// file at the root that is not instructions.md.
const prompts = {};
for (const f of readdirSync(join(ROOT, "agent")).filter((n) => /^prompt-[a-z0-9-]+\.md$/.test(n)).sort()) prompts[f.slice("prompt-".length, -3)] = readFileSync(join(ROOT, "agent", f), "utf8");
const subagents = {};
{
  const dir = join(ROOT, "agent/subagents");
  for (const key of readdirSync(dir).sort()) {
    const p = join(dir, key, "prompt.md");
    if (existsSync(p)) subagents[key] = readFileSync(p, "utf8");
  }
}
const sorted = (o) => Object.fromEntries(Object.entries(o).sort(([a], [b]) => a.localeCompare(b)));
const body = `// AUTO-GENERATED by scripts/gen-prompts.mjs from agent/prompt-*.md and agent/subagents/*/prompt.md — do not edit by hand.

/** The root prompt's authored parts, by file name (agent/lib/root-instructions.ts assembles them). */
export const PROMPTS: Record<string, string> = ${JSON.stringify(sorted(prompts), null, 2)};

/** Each base specialist's authored prompt, by subagent key (its instructions.ts speaks it in the profile's words). */
export const SUBAGENT_PROMPTS: Record<string, string> = ${JSON.stringify(sorted(subagents), null, 2)};
`;
writeFileSync(join(ROOT, "agent/lib/prompts.generated.ts"), body);
console.log(`prompts: ${Object.keys(prompts).length} root part(s), ${Object.keys(subagents).length} specialist prompt(s) -> agent/lib/prompts.generated.ts`);
