// AUTO-GENERATED by scripts/gen-deployment-profile.mjs from profiles/*.json — do not edit by hand.
// Sources, in merge order: 00-default.json

export interface DeploymentProfile {
  product: { name: string; tagline: string; description: string };
  vocabulary: {
    account: { singular: string; plural: string };
    member: { singular: string; plural: string };
    owner: string;
    account_context: string;
  };
  chat: {
    hero_lines: string[];
    empty_sections: { urgent: string; stalled: string };
    /** Long messages a person SENT start folded to collapsed_lines lines, with "Show more". Assistant replies never fold. */
    user_messages: { collapse: boolean; collapsed_lines: number };
    starter_cards: {
      owner_label: string; ticket_waiting: string; tickets_waiting: string; ticket_badge: string; tickets_badge: string;
      triage_title: string; triage_prompt: string;
      quiet_summary: string; quiet_summary_long: string; quiet_badge: string; quiet_title: string; quiet_prompt: string;
    };
    /** pill_active / pill_locked take {context} (vocabulary.account_context) and {names}. */
    account_search: {
      title: string; description: string; placeholder: string; empty: string;
      pill_empty: string; pill_active: string; pill_locked: string;
    };
  };
  dataroom: {
    root_label: string;
    domains: Record<string, { label: string; visible: boolean; description?: string }>;
    /** null = the built-in starter tree; otherwise the files a new workspace is seeded with. */
    seed: { path: string; content: string }[] | null;
  };
  /** Sent to the model on every turn, after the stable prompt. null = nothing extra. */
  agent: { briefing: string | null };
}

export const DEPLOYMENT_PROFILE: DeploymentProfile = {
  "product": {
    "name": "Delivered",
    "tagline": "The operations console for forward-deployed teams.",
    "description": "{product} — the FDE operations console: an eve-powered agent that runs customer onboarding, deployments, and the data room for the forward-deployed team."
  },
  "vocabulary": {
    "account": {
      "singular": "customer",
      "plural": "customers"
    },
    "member": {
      "singular": "FDE",
      "plural": "FDEs"
    },
    "owner": "FDE owner",
    "account_context": "Customer context"
  },
  "chat": {
    "hero_lines": [
      "{product}",
      "What needs doing today?",
      "Prep the stand-up",
      "Chase the follow-ups",
      "Keep every customer close"
    ],
    "empty_sections": {
      "urgent": "Urgent tickets",
      "stalled": "Stalled customers"
    },
    "user_messages": {
      "collapse": true,
      "collapsed_lines": 6
    },
    "starter_cards": {
      "owner_label": "FDE owner",
      "ticket_waiting": "One open ticket is waiting on us.",
      "tickets_waiting": "{count} open tickets are waiting on us.",
      "ticket_badge": "1 open",
      "tickets_badge": "{count} open",
      "triage_title": "Triage the open tickets",
      "triage_prompt": "Triage the open tickets for {name}: what is blocking each one, who owns it, and what should we do next?",
      "quiet_summary": "No contact logged in {days} days.",
      "quiet_summary_long": "No contact logged for over a month.",
      "quiet_badge": "{days}d quiet",
      "quiet_title": "Draft a check-in",
      "quiet_prompt": "{name} has been quiet for {days} days. Summarise where we left off and draft a check-in to their main contact."
    },
    "account_search": {
      "title": "Customer context",
      "description": "Pick the customers this conversation is about — the agent grounds itself in their record.",
      "placeholder": "Search customers…",
      "empty": "No customers found.",
      "pill_empty": "Set the customer context for this chat",
      "pill_active": "{context}: {names} — click to change",
      "pill_locked": "{context} is locked for this chat: {names}"
    }
  },
  "dataroom": {
    "root_label": "Data Room",
    "domains": {
      "Customers": {
        "label": "Customers",
        "visible": true
      },
      "Platform": {
        "label": "Platform",
        "visible": true
      },
      "Deployments": {
        "label": "Deployments",
        "visible": true
      },
      "Solutions": {
        "label": "Solutions",
        "visible": true
      },
      "Implementation": {
        "label": "Implementation",
        "visible": true
      },
      "Tickets": {
        "label": "Tickets",
        "visible": true
      },
      "People": {
        "label": "People",
        "visible": true
      }
    },
    "seed": null
  },
  "agent": {
    "briefing": null
  }
};

/** The product's display name. One place, so a rebrand is a profile, not a search-and-replace. */
export const PRODUCT_NAME: string = DEPLOYMENT_PROFILE.product.name;

/** Fill {name}-style slots in profile copy. Unknown slots are left as written. */
export function fillProfileText(text: string, slots: Record<string, string | number> = {}): string {
  return text.replace(/\{([a-z_]+)\}/g, (whole, key) => (key === "product" ? PRODUCT_NAME : key in slots ? String(slots[key]) : whole));
}
