import { NextRequest, NextResponse } from "next/server";
import { errorMessage, errorText, zodMessage } from "@/lib/ops-errors";
import { and, asc, eq, isNull } from "drizzle-orm";
import { z } from "zod";
import { apps } from "@/agent/lib/db/schema";
import { cronMatches } from "@/agent/lib/cron-match";
import { recordOpsAudit } from "@/lib/ops-audit";
import { getOpsDb, withOrgRls } from "@/lib/ops-db";
import { orgContextForRequest } from "@/lib/org-context";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * GET  /api/ops/apps — every live app, oldest first (stable list order).
 * POST /api/ops/apps — create one. An app is a Markdown document regenerated by
 * either a WORKFLOW or a PROMPT; `refreshCron` (5-field UTC) drives automatic
 * refreshes, and is validated here before it can ever be persisted.
 */
const createAppSchema = z.strictObject({
  name: z.string().min(1),
  description: z.string().nullable().optional(),
  sourceKind: z.enum(["workflow", "prompt"]).default("prompt"),
  workflow: z.string().nullable().optional(),
  prompt: z.string().nullable().optional(),
  subagent: z.string().nullable().optional(),
  customerId: z.string().nullable().optional(),
  refreshCron: z.string().nullable().optional(),
  enabled: z.boolean().optional(),
  createdBy: z.string().min(1).default("web"),
});


/** "Weekly QBR digest" → "weekly-qbr-digest" (url-safe, stable handle). */
export function slugify(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "app"
  );
}

export async function GET(request: NextRequest) {
  const ctx = await orgContextForRequest(request);
  if (!ctx) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  if (ctx instanceof Response) return ctx;
  if (!getOpsDb()) return NextResponse.json({ items: [] });
  try {
    const items = await withOrgRls(ctx.orgId, (tx) =>
      tx.select().from(apps).where(and(eq(apps.orgId, ctx.orgId), isNull(apps.deletedAt))).orderBy(asc(apps.createdAt)),
    );
    return NextResponse.json({ items });
  } catch (e) {
    return NextResponse.json({ error: errorText(e) }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  const ctx = await orgContextForRequest(request);
  if (!ctx) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  if (ctx instanceof Response) return ctx;
  const db = getOpsDb();
  if (!db) return NextResponse.json({ error: "Database not configured" }, { status: 503 });
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }
  const parsed = createAppSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: zodMessage(parsed.error) }, { status: 400 });
  }
  const data = parsed.data;

  // A source that produces nothing would refresh into an empty document.
  if (data.sourceKind === "workflow" && !data.workflow?.trim()) {
    return NextResponse.json({ error: "Pick the workflow that generates this app." }, { status: 400 });
  }
  if (data.sourceKind === "prompt" && !data.prompt?.trim()) {
    return NextResponse.json({ error: "Say what this app should generate." }, { status: 400 });
  }
  // Validate the cadence BEFORE it is persisted — an unparseable expression
  // would silently never fire.
  if (data.refreshCron) {
    try {
      cronMatches(data.refreshCron, new Date());
    } catch (e) {
      return NextResponse.json(
        { error: errorMessage(e) },
        { status: 400 },
      );
    }
  }

  try {
    const [item] = await withOrgRls(ctx.orgId, (tx) =>
      tx
        .insert(apps)
        .values({ ...data, orgId: ctx.orgId, slug: slugify(data.name) })
        .returning(),
    );
    await recordOpsAudit(db, {
      automationType: "workflow",
      automationId: item.id,
      actor: data.createdBy,
      event: `Created app "${item.name}" (${item.sourceKind})`,
      orgId: ctx.orgId,
    });
    return NextResponse.json({ item }, { status: 201 });
  } catch (e) {
    return NextResponse.json({ error: errorText(e) }, { status: 500 });
  }
}
