/**
 * The pure parts of the per-deployment agent package build (scripts/build-agent-cli.mjs):
 * input validation, the deployment module, dm.md rendering, SKILL.md validation and the
 * safety gate. No reads of the repo and no writes here, so scripts/test-agent-cli-build.mjs
 * can exercise each rule directly. See docs/AGENT_CLI.md.
 */
import { createHash } from "node:crypto";
import { isDeepStrictEqual } from "node:util";

// ------------------------------------------------------------------ inputs

/** npm's naming rules (validate-npm-package-name, "new packages"), including scopes. Returns a list of problems. */
export function npmNameProblems(name) {
  const out = [];
  if (typeof name !== "string" || !name.length) return ["name is required"];
  if (name.length > 214) out.push("name is longer than 214 characters");
  if (name !== name.toLowerCase()) out.push("name must be lowercase");
  if (name.trim() !== name) out.push("name has leading or trailing spaces");
  const m = /^(?:@([^/]+)\/)?([^/]+)$/.exec(name);
  if (!m) return [...out, 'name must be "<name>" or "@<scope>/<name>"'];
  for (const [what, part] of [["scope", m[1]], ["name", m[2]]]) {
    if (part === undefined) continue;
    if (/^[._]/.test(part)) out.push(`${what} cannot start with "." or "_"`);
    if (!/^[a-z0-9._~-]+$/.test(part)) out.push(`${what} "${part}" has characters that are not URL-safe (allowed: a-z 0-9 . _ ~ -)`);
    if (/[~'!()*]/.test(part)) out.push(`${what} cannot contain ~'!()*`);
  }
  if (!m[1] && ["node_modules", "favicon.ico"].includes(m[2])) out.push(`"${m[2]}" is a reserved name`);
  if (!m[1] && NODE_CORE.has(m[2])) out.push(`"${m[2]}" is a Node.js core module name`);
  return out;
}
const NODE_CORE = new Set("assert buffer child_process cluster console constants crypto dgram dns domain events fs http http2 https module net os path perf_hooks process punycode querystring readline repl stream string_decoder sys timers tls tty url util v8 vm worker_threads zlib".split(" "));

/** "@scope/name" -> "name": the bin npx runs for `npx <package>`. */
export const unscopedName = (name) => name.replace(/^@[^/]+\//, "");

const SEMVER = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/;
export const isSemver = (v) => typeof v === "string" && SEMVER.test(v);

/** The deployment's address: https, a host, nothing else. Returns { origin } or { problem }. */
export function parseOrigin(raw) {
  if (typeof raw !== "string" || !raw.trim()) return { problem: "origin is required" };
  let u;
  try { u = new URL(raw.trim()); } catch { return { problem: `"${raw}" is not a URL` }; }
  if (u.protocol !== "https:") return { problem: `origin must be https (got ${u.protocol}//)` };
  if (u.username || u.password) return { problem: "origin must not carry credentials" };
  if (u.pathname !== "/" || u.search || u.hash) return { problem: `origin must be an address only, with no path, query or fragment (got "${raw}")` };
  if (!u.hostname.includes(".")) return { problem: `origin host "${u.hostname}" is not a public host name` };
  return { origin: u.origin };
}

// ------------------------------------------------------------------ the deployment module

/**
 * deployment.generated.mjs: the ONE module setup/*.mjs read every product word and the
 * default address from. `commands` are the command names the help text shows.
 */
export function renderDeploymentModule(d) {
  const data = {
    packageName: d.packageName,
    name: d.name,
    slug: d.slug,
    tagline: d.tagline ?? null,
    origin: d.origin ?? null,
    mcpEndpoint: d.mcpEndpoint ?? null,
    vocabulary: d.vocabulary,
    commands: d.commands,
    connect: d.connect ?? null,
  };
  return `// AUTO-GENERATED by scripts/build-agent-cli.mjs - do not edit by hand.
// Everything in this package that names a product or an address. setup/ ships the DEFAULT
// (no address, the base product's wording); a package built for one deployment carries that
// deployment's. See docs/AGENT_CLI.md.
export const DEPLOYMENT = ${JSON.stringify(data, null, 2)};
export const { packageName, name, slug, tagline, origin, mcpEndpoint, vocabulary, commands, connect } = DEPLOYMENT;
`;
}

/** What setup/deployment.generated.mjs holds: today's generic package. */
export function defaultDeployment({ packageName, profile, slug }) {
  return {
    packageName,
    name: profile.product.name,
    slug,
    tagline: null,
    origin: null,
    mcpEndpoint: null,
    vocabulary: profile.vocabulary,
    commands: { login: "fde-login", mcp: "fde-mcp", installSkills: "install-skill" },
    connect: null,
  };
}

// ------------------------------------------------------------------ dm.md

const DOMAIN_LINE = /^ {2}\|-([A-Za-z]+)[ \t]*$/;
/** Which record area lives in which data-room folder. */
const AREA_FOLDER = { deployments: "Deployments", implementations: "Implementation" };

/**
 * The package's dm.md: the repo's dm.md as THIS deployment shows it. Hidden domains are
 * removed; a relabelled one reads "Label [Folder]" (the bracketed name is the real one a
 * tool's path uses); redefined record areas are summarised and lose the default tree under their folder; subagent path templates are
 * appended under their domain. Under the default profile with no templates the result is
 * the source, byte for byte.
 */
export function renderDmMd({ source, profile, defaultDomains, extraTemplates = [], productName }) {
  const lines = source.split("\n");
  const blocks = []; // { folder, lines }
  let head = [];
  let cur = null;
  for (const line of lines) {
    const m = DOMAIN_LINE.exec(line);
    if (m) { cur = { folder: m[1], lines: [line] }; blocks.push(cur); } else if (cur) cur.lines.push(line); else head.push(line);
  }
  const domains = profile.dataroom.domains;
  const extrasByFolder = new Map();
  for (const t of extraTemplates) {
    const [folder, ...rest] = t.split("/");
    if (!extrasByFolder.has(folder)) extrasByFolder.set(folder, []);
    extrasByFolder.get(folder).push(rest.join("/"));
  }
  const unknown = [...extrasByFolder.keys()].filter((f) => !blocks.some((b) => b.folder === f));
  if (unknown.length) throw new Error(`dm.md: a subagent path template starts with ${unknown.join(", ")}, which is not a domain in dm.md`);

  const hidden = blocks.filter((b) => domains[b.folder]?.visible === false).map((b) => b.folder);
  const relabelled = blocks.filter((b) => domains[b.folder]?.visible !== false && domains[b.folder]?.label && domains[b.folder].label !== b.folder);
  const redefined = Object.keys(AREA_FOLDER).filter((a) => !isDeepStrictEqual(profile.domains[a], defaultDomains[a]));
  if (!hidden.length && !relabelled.length && !redefined.length && !extraTemplates.length) return source;

  const out = [];
  out.push(`${productName} data room.`);
  out.push("A name in [brackets] is the REAL folder name. Every path you pass to a tool uses the real name, never the label in front of it.");
  if (hidden.length) out.push(`Not used in this deployment, so not listed: ${hidden.join(", ")}.`);
  for (const a of redefined) {
    const d = profile.domains[a];
    const shown = a === "implementations" && d.group_by ? d.group_label.plural : d.label.plural;
    const rows = a === "implementations" && d.group_by ? `; each row is a ${d.label.singular}` : "";
    out.push(`${shown} (stored as ${AREA_FOLDER[a]}${rows}): ${d.description}`);
  }
  out.push("");
  out.push(...head);
  for (const b of blocks) {
    const spec = domains[b.folder];
    const extras = extrasByFolder.get(b.folder) ?? [];
    const isHidden = spec?.visible === false;
    if (isHidden && !extras.length) continue;
    // A redefined record area keeps its rows in the database; the default tree under its folder describes
    // the DEFAULT meaning of the area, so listing it would describe files this deployment never has.
    const isRedefined = redefined.some((a) => AREA_FOLDER[a] === b.folder);
    const kept = b.lines.slice(1);
    const body = isHidden ? [] : isRedefined
      ? ["    (records, not files: read and write them with the record tools; nothing is laid out under this folder by default)", ...kept.filter((l) => l.trim() === "")]
      : kept;
    // Keep the blank lines that end a block at its end, after anything appended.
    let tail = 0;
    while (tail < body.length && body[body.length - 1 - tail].trim() === "") tail++;
    const label = spec?.label && spec.label !== b.folder ? `${spec.label} [${b.folder}]` : b.folder;
    const note = isHidden ? " (not shown in the app; a subagent writes here)" : spec?.description ? ` (${spec.description})` : "";
    out.push(`  |-${label}${note}`);
    out.push(...body.slice(0, body.length - tail));
    for (const e of extras) out.push(`    |-${e} (added by a subagent)`);
    out.push(...body.slice(body.length - tail));
  }
  return out.join("\n");
}

// ------------------------------------------------------------------ skills

/**
 * SKILL.md frontmatter, checked the way a YAML parser and the skills CLI would read it.
 * Returns { name, description } or throws with the file named.
 */
export function parseSkillFrontmatter(text, where) {
  const fm = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/.exec(text);
  if (!fm) throw new Error(`${where}: missing YAML frontmatter (--- ... --- at the top)`);
  const fields = {};
  const rows = fm[1].split(/\r?\n/);
  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    if (!row.trim() || row.trimStart().startsWith("#")) continue;
    if (/^\s/.test(row)) continue; // continuation / nested value of the previous key
    const kv = /^([A-Za-z0-9_-]+):(?:\s+(.*))?$/.exec(row);
    if (!kv) throw new Error(`${where}: frontmatter line ${i + 1} is not "key: value": ${row}`);
    let value = (kv[2] ?? "").trim();
    if (/^[>|][+-]?$/.test(value) || value === "") {
      const block = [];
      while (i + 1 < rows.length && (/^\s+\S/.test(rows[i + 1]) || !rows[i + 1].trim())) block.push(rows[++i].trim());
      value = block.join(" ").trim();
    } else if (value.startsWith('"')) {
      try { value = JSON.parse(value); } catch { throw new Error(`${where}: ${kv[1]} is not a valid double-quoted YAML string`); }
    } else if (value.startsWith("'")) {
      if (!value.endsWith("'") || value.length < 2) throw new Error(`${where}: ${kv[1]} has an unclosed single quote`);
      value = value.slice(1, -1).replace(/''/g, "'");
    } else {
      if (/: |:$/.test(value)) throw new Error(`${where}: ${kv[1]} contains ": " and is not quoted, which is not valid YAML. Wrap the value in double quotes.`);
      if (/ #/.test(value)) throw new Error(`${where}: ${kv[1]} contains " #", which YAML reads as a comment. Wrap the value in double quotes.`);
      if (/^[[\]{}&*!|>%@`,?-] ?/.test(value) && !/^-\S/.test(value)) throw new Error(`${where}: ${kv[1]} starts with a character YAML treats specially. Wrap the value in double quotes.`);
    }
    fields[kv[1]] = value;
  }
  const { name, description } = fields;
  if (!name || !description) throw new Error(`${where}: frontmatter needs both name and description`);
  if (!/^[a-z0-9-]{1,64}$/.test(name)) throw new Error(`${where}: name "${name}" must match ^[a-z0-9-]{1,64}$ (the skills CLI rejects others)`);
  if (description.length > 1024) throw new Error(`${where}: description is ${description.length} characters; the skills CLI caps it at 1024`);
  return { name, description };
}

// ------------------------------------------------------------------ the safety gate

/** Third-party hosts the CLI legitimately names. Everything else that is not --origin is "another deployment". */
export const ALLOWED_HOSTS = [
  "accounts.google.com", // fde-login: the Google sign-in page
  "oauth2.googleapis.com", // fde-login / fde-mcp: token exchange and refresh
  "mcp.linear.app", // fde-tools: the example in a bring-your-own connector's description
  "developers.google.com", // README: Google's note on installed-app client secrets
  "127.0.0.1", // fde-login: the loopback OAuth callback
  "localhost",
];
/** Reserved for documentation (RFC 2606): never a real deployment. */
const PLACEHOLDER_HOST = /(^|\.)example\.(com|org|net)$/;
/** Placeholder addresses the connect instructions print (lib/mcp-connect.ts). */
const PLACEHOLDER_EMAILS = new Set(["you@company.com", "name@company.com"]);

/** Files a package may contain: exact paths, and extensions allowed under skills/. */
export const ALLOWED_FILES = ["package.json", "README.md", "dm.md", "deployment.generated.mjs", "fde-cli.mjs", "fde-login.mjs", "fde-mcp.mjs", "fde-tools.mjs", "fde-install-skill.mjs"];
export const ALLOWED_SKILL_EXTENSIONS = [".md", ".json", ".txt", ".yaml", ".yml", ".csv"];

/**
 * The Google installed-app client secret in fde-login.mjs / fde-mcp.mjs is public by
 * design (Google: "not treated as a secret") and is the client the server verifies.
 * Any OTHER GOCSPX- value is a finding. Compared by digest so the gate does not repeat it.
 */
export const KNOWN_INSTALLED_APP_SECRET_SHA256 = "bc1a762fde41fff47a81bccb0a7c68ceff34a6bfe3bd518cf5a8a7ea370ccce8";

const SECRET_SHAPES = [
  ["Resend API key (re_…)", /\bre_[A-Za-z0-9]{16,}\b/g],
  ["Cloudflare user token (cfut_…)", /\bcfut_[A-Za-z0-9_-]{16,}/g],
  ["API key (sk-…)", /\bsk-[A-Za-z0-9_-]{20,}/g],
  ["AWS access key id (AKIA…)", /\bAKIA[0-9A-Z]{16}\b/g],
  ["private key block", /-----BEGIN [A-Z ]*PRIVATE KEY-----/g],
  ["bearer token", /\bBearer\s+[A-Za-z0-9._~+/-]{24,}=*/g],
  ["database URL with a password", /\bpostgres(?:ql)?:\/\/[^\s:@/]+:[^\s@]+@/g],
  ["JSON Web Token", /\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}/g],
  ["GitHub token", /\bgh[pousr]_[A-Za-z0-9]{30,}\b/g],
  ["Slack token", /\bxox[abprs]-[A-Za-z0-9-]{10,}/g],
  ["Vercel Blob token", /\bvercel_blob_rw_[A-Za-z0-9_]{10,}/g],
  ["Google OAuth client secret", /\bGOCSPX-[A-Za-z0-9_-]{20,}/g],
];
// The last label must be letters, so "cli@0.12.0" (a package at a version) is not an address.
const EMAIL = /[A-Za-z0-9._%+-]+@[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)*\.[A-Za-z]{2,}/g;
const URL_RE = /https?:\/\/[^\s"'`<>)\]},\\]+/g;
const redact = (s) => (s.length <= 12 ? s : `${s.slice(0, 8)}…(${s.length} chars)`);
const sha256 = (s) => createHash("sha256").update(s).digest("hex");

/**
 * Check a built package. `files` is [{ path, bytes: Buffer, symlink?: boolean }] with
 * POSIX relative paths. Returns a list of offender strings; empty means it may be published.
 */
export function safetyGate(files, { origin, allowHosts = [], allowEmails = [], foreignPackageNames = [] }) {
  const offenders = [];
  const hosts = new Set([...ALLOWED_HOSTS, ...allowHosts.map((h) => h.replace(/^https?:\/\//, "").replace(/\/.*$/, "")), new URL(origin).host]);
  const emails = new Set([...PLACEHOLDER_EMAILS, ...allowEmails.map((e) => e.toLowerCase())]);
  for (const f of files) {
    const p = f.path;
    const base = p.split("/").at(-1);
    const ext = base.includes(".") ? base.slice(base.lastIndexOf(".")).toLowerCase() : "";
    if (f.symlink) { offenders.push(`${p}: a symbolic link (a package ships files, not links)`); continue; }
    if (/^\.env/i.test(base) || /\.env$/i.test(base)) offenders.push(`${p}: an environment file`);
    if (/-spec\.md$/i.test(base)) offenders.push(`${p}: a "-spec.md" rulebook is operator material and never ships`);
    if (p.split("/").slice(0, -1).includes("schemas")) offenders.push(`${p}: a file under a schemas/ directory is operator material and never ships`);
    const inSkills = p.startsWith("skills/") && p.split("/").length >= 3;
    const allowed = ALLOWED_FILES.includes(p) || (inSkills && ALLOWED_SKILL_EXTENSIONS.includes(ext));
    if (!allowed) offenders.push(`${p}: not on the allowlist (allowed: ${ALLOWED_FILES.join(", ")}; under skills/<name>/: ${ALLOWED_SKILL_EXTENSIONS.join(" ")})`);
    if (f.bytes.includes(0)) { offenders.push(`${p}: binary content`); continue; }
    const text = f.bytes.toString("utf8");
    const lineOf = (index) => text.slice(0, index).split("\n").length;
    for (const [what, re] of SECRET_SHAPES) {
      for (const m of text.matchAll(re)) {
        if (what === "Google OAuth client secret" && sha256(m[0]) === KNOWN_INSTALLED_APP_SECRET_SHA256) continue;
        offenders.push(`${p}:${lineOf(m.index)}: looks like a ${what}: ${redact(m[0])}`);
      }
    }
    for (const m of text.matchAll(EMAIL)) {
      const e = m[0].toLowerCase().replace(/\.$/, "");
      if (emails.has(e) || PLACEHOLDER_HOST.test(e.split("@")[1])) continue;
      offenders.push(`${p}:${lineOf(m.index)}: an email address that is not on the allowlist: ${m[0]}`);
    }
    for (const m of text.matchAll(URL_RE)) {
      const raw = m[0].replace(/[.;:!?]+$/, "");
      if (/[${]/.test(raw.replace(/^https?:\/\//, "").split("/")[0])) continue; // a template, e.g. https://${host}
      let u;
      try { u = new URL(raw); } catch { continue; }
      if (!u.hostname || u.hostname === "…") continue;
      if (hosts.has(u.host) || hosts.has(u.hostname) || PLACEHOLDER_HOST.test(u.hostname)) continue;
      offenders.push(`${p}:${lineOf(m.index)}: an address that is not this deployment's (${origin}) or a listed third-party host: ${u.origin}`);
    }
    for (const name of foreignPackageNames) {
      let at = text.indexOf(name);
      while (at > -1) {
        // "@a/cli" inside "@a/cli-tools" is a different package.
        if (!/[a-z0-9._~-]/i.test(text[at + name.length] ?? "")) offenders.push(`${p}:${lineOf(at)}: names another package (${name})`);
        at = text.indexOf(name, at + name.length);
      }
    }
  }
  return offenders;
}

/** manifest.json: what a publisher diffs between releases. */
export function buildManifest({ name, version, origin, files }) {
  const list = files.map((f) => ({ path: f.path, bytes: f.bytes.length, sha256: sha256(f.bytes) })).sort((a, b) => (a.path < b.path ? -1 : 1));
  return { name, version, origin, fileCount: list.length, totalBytes: list.reduce((n, f) => n + f.bytes, 0), files: list };
}
export { sha256 };
